### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by tecosaur** [magit/magit.vc#12]
Hello!

I've been making a draft article for Magit on Wikipedia, and it would be nice to use some of the screenshots here.
I currently can't because (as far as I can tell) they aren't appropriately licenced (needs CC-BY 4.0 etc).

It would be great if the content of the site could be released as such :smiley: 

Many thanks for your work making Magit an indispensable part of my workflow!

**Comment by tarsius** [comment]
> I've been making a draft article for Magit on Wikipedia,

Thanks a lot for doing that.

> and it would be nice to use some of the screenshots here. I currently can't because (as far as I can tell) they aren't appropriately licenced (needs CC-BY 4.0 etc).

I'll do that. At a later time I might create some new ones too.

On twitter [I mentioned](https://twitter.com/magit_emacs/status/1306366186234445824) a few "independent references", but I think you already saw that.

Some feedback on the article:

* Magit is not the 3rd most founded it is the 27th. https://www.kickstarter.com/discover/advanced?category_id=51&woe_id=0&sort=most_funded&seed=2667164&page=3 links to page 3 and there's a dozen projects per page.
* Don't talk about it being a porcelain. Every time there's discussion about magit, there's someone who freaks out about that term. I'll probably stop using it as well.
* When talking about GUIs also mention TUIs. (There's a mention in "Notes", but why not move that information up?)
* IMO at least currently the information about Forges takes up to much space. I would reduce these lists into a single unstyled paragraph, for now at least.

**Comment by tarsius** [comment]
I have licensed the screenshots on https://emacsair.me/2017/09/01/magit-walk-through/
under CC-BY 4.0. I'll have to think a bit more about licensing before applying that or something else to the rest of the page.

**Comment by npostavs** [comment]
> is currently the 27th most funded software project on kickstarter

Wouldn't phrasing it in terms of "Xth most funded project *at the time*" be more useful (and wouldn't go out of date)?

**Comment by tarsius** [comment]
I'm just gonna leave it as is. The manuals are already released under GPLv3+ and most of the other content is either generated or collected from elsewhere. Except for the manuals most useful content is actually hosted elsewhere and this page just links to it.

I've someone doesn't feel comfortable just using some content then they'll just have to ask.
